sudo: required

language: go

services:
  - docker

before_install:
- docker pull jbenet/go-ipfs:latest
- docker run -v $HOME/ipfs:/data/ipfs -p 8080:8080 -p 4001:4001 -p 5001:5001 jbenet/go-ipfs
- docker ps -a

install:
  - go get -t -v ./...
